os:
  - linux
  - osx
sudo: required
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '6'
  - '7'
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc48; fi'
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CC=g++-4.8; export CXXFLAGS=-std=c++11; fi
  - echo $CC
  - echo $CXX
  - echo $CXXFLAGS
before_script:
  - npm install winston@2.3.0
  - 'npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production'
env:
  - CXX=g++-4.8 CXXFLAGS=-std=c++11 DEBUG=true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
